services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  test_db:
    image: postgres:15
    container_name: postgres-test-db
    environment:
      POSTGRES_USER: my_test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: my_test_db
    ports:
      - "5433:5432"  # Expose to host on 5433
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  test_postgres_data: